version: '3'

services:

  db:
    image: postgres
#    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    tty: true
    restart: always
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile