version: '3.7'

services:

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=flower
      - POSTGRES_DB=flower
    tty: true
    restart: always
    user: postgres
    volumes:
      - ./assets/schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flower"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s

  register:
    ports:
      - 8000:8000
    container_name: register
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: assets/dockerfiles/register/Dockerfile

  watcher:
    container_name: watcher
    depends_on:
      - db
    build:
      context: .
      dockerfile: assets/dockerfiles/watcher/Dockerfile